name: DeployApp
run-name: ${{ github.actor }} Deploying app
on: 
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: 'dist'
  #         path: 'dist/**'
  #         if-no-files-found: error
  #         retention-days: 90
          
  # ListContent:
  #   needs: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: 'dist'
  #     - name: Content
  #       run: ls -la
      